version: 2
jobs:
  build:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore-cache:
          name: Restore cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: yarn install
      - save-cache:
          name: Save cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: yarn test
  deploy:
    working_directory: ~/frontend
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "b9:24:92:ed:aa:09:92:61:4e:ec:99:c5:a4:45:ff:ca"
      - run:
          name: Setup heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Add heroku remote
          command: heroku git:remote -a ucll-cc-frontend
      - run:
          name: Push it to heroku
          command: git push heroku master
      - run:
          name: Restart heroku
          command: heroku restart


workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build
